---

- debug: msg="Creating Docker image based on Docker-agnostic Ansible play"
- debug: var=andock_image
- debug: var=andock_role

- name: Get list of Docker images known to the Docker host
  shell: "{{ andock_cmd_docker }} images"
  args:
    executable: "/bin/bash"
  register: andock_images
#- debug: var=andock_images.stdout_lines

- set_fact: needle="{{ andock_image }} " # append a space to avoid false positives

- name: Determine if the image we're creating already exists
  set_fact: andock_image_missing={{ andock_images.stdout.find(needle) == -1 }}

- include: build.yml
  when: andock_image_missing or andock_rebuild|default(False)
