# Assumption: either "phusion/baseimage"
# or a derivative of it
FROM {{ andock_parent_image }}

# Ensure Python is installed (Ansible requirement)
RUN which python || apt-get update && apt-get -y install python

# Ensure sshd is configured to start and uses unique host keys
RUN rm -f /etc/service/sshd/down && /etc/my_init.d/00_regen_ssh_host_keys.sh > /dev/null 2>&1

# Optionallty add an SSH public key to ~/.ssh/authorized_keys
{% if andock_identity_file|default(false) %}
    RUN mkdir -p /root/.ssh
    ADD andock_identity_file.pub /tmp/andock_identity_file.pub
    RUN cat /tmp/andock_identity_file.pub >> /root/.ssh/authorized_keys && rm -f /tmp/andock_identity_file.pub
{% endif %}

# Init the phusion/baseimage way
CMD [ "/sbin/my_init" ]
